import React from "react";
import "../styles/globals.css";
import Script from "next/script";

export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-QP83KP2952"
        />
        <Script id="google-analytics">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-QP83KP2952');
          `}
        </Script>
        <title>Crypto-Tobi</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
